### ISSUE TITLE
Ask a question about Er.v and "then they wait until g(V r,v ) ≥ E r−1,v"

### ISSUE THREAD

**Issue by james-ray** [w3f/consensus#12]
Hi, I have read the pdf, and a little confused about this description.

We define E r,v to be v’s estimate of what might have been finalised in round r given by the last block in
the chain with head g(V r,v ) for which it is possible for C r,r to have a supermajority.

My question is:
1. How to understand "it is possible for C r,r to have a supermajority.",  plus I think here Cr,r should be a print error, it should be Cr,v.  I can understand Cr,v have a supermajority or not have a supermajority on a block, but I don't quite understand it is possible for Cr,v to have a supermajority, I think maybe it means it is NOT impossible for Cr,v to have a supermajority on B. In this case, even Cr,v currently is an empty set, I can still say it is possible for it to have a supermajority on any block.
2. At the moment of judging round r is completable,  we should have a Er,v at that time, could it change later? The Er,v is a very important judge factor, prevote of r should based on Er-1,v and precommit should wait until g(V r,v ) ≥ E r−1,v. If it do can change, can it change to lower? or could only change to higher?

Thanks in advance!

**Comment by james-ray** [comment]
@AlistairStewart 
In the paper of grandpa, there is a description about liveness and Deadlock

Corollary 4.3. If there at most f Byzantine voters in any vote, B was finalised in round r, and an honest
participant v sees that round r 0 ≥ r is completable, then E r 0 ,v ≥ B.

I have a question about it, assume at some round r, there is a global total prevote set S, in which 2/3 can conclude a higher g(S1) and another 2/3 in it can only conclude a lower g(S2), <1/3 nodes only see S2 so they precommit g(S2), >2/3 nodes see S1 so they precommit g(S1), but the g(S1) precommits transferred very slowly, so only 1 node sees them thus he finalize a higher block B, the other nodes only see a precommit set combined with g(S1) and g(S2), so they finalize a lower block A.

In the next round , most nodes which finalized block A will prevote for a block > A, but this block could < B, so how can we ensure the waiting

. If v is a voter for the precommit step in round r, then they wait until g(V r,v ) ≥ E r−1,v
(in the only node's view, E r-1,v is B.)

can wait to success?

I mean, that only node which finalized B will forever hang there?

**Comment by AlistairStewart** [comment]
Hi,

In answer to your previous questions, the most important point is that for 2), E_r,v can only change to earlier after round r completes and we may indeed need to wait for it to change to earlier to progress.

>In the next round , most nodes which finalized block A will prevote for a block > A,

No, they won't if there are only f Byzantine voters by that Corollary. So what happens? Well most nodes see S_2 and don't finalise B before the prevote. But according to the corollary, it is still true that they have E_{r-1,v} >= B.

The point here is that even though S_2 does not have a supermajority for B, it should still be possible for it to have a supermajority for B. Possibility here is indeed the negation of impossibility (in answer to 1), so possibility means that it is not true that S_2 has 2/3 votes >= B. 

Why not? Because S_1 and S_2 should overlap, if only f voters equivocate. And this overlap must have enough votes >= B to rule out impossibility. As a result all honest voters have E_{r,v-1} >= B and prevote >= B.

Let's imagine how this scenario might happen. Suppose some voter v is a long way behind because they have bad network or are having trouble syncing or something. And most voters see a set S_2 which has n-f-1 votes for B, just short of a supermajority during round r itself. Then when v gets to round r, they can precommit for B themselves and then get a set S_1 that can finalise it in round r, which no-one else did (yet), maybe when everyone else is many rounds ahead. But that's okay, because most validators see that it is possible for S_2 to have a supermajority for v and they'll have E_{r,v} >= B in round r+1, so they'll prevote and precommit >= B, which should mean that they all finalise it in round r+1 anyway.

**Comment by james-ray** [comment]
@AlistairStewart  Really thanks for your clarification. I appreciate it and I'll seize the chance to ask you some more questions :)  

I think Er,v can both change to higher or lower,
Er,v do can change to higher, if it later receive more prevotes, it can deduce to a higher g(Vr,v).
And the Er,v can also change to lower, if it later receive more precommits, it deduces that g(Vr,v) is impossible, and then g(Vr,v)-1 is impossible, etc... , so his Er,v changes to lower.
But once Er,v changes to lower, it cannot change to higher again, nor can it change to another fork chain. and once it decreases to lower than g(Vr,v), we can complete this round


I don't know if my understanding is correct, and I also want to confirm the following scenario: 

If at some round, 1/2 nodes precommit a higher branch block B and 1/2 nodes precommit a lower joint common chain block A, first 1/2 nodes will set their Er,v to be B initially, then along with their receiving of precommit, they will gradually realize that branch B is impossible,  We can deduce that g(Vr+1,v) must at the lower joint common chain, it does not meet his requirement g(Vr+1,v) must >= his E(r,v), so he will continue receive round r's precommit and decrease his E(r,v) until it is low enough to let him accept g(Vr+1,v) ?

Is this what you said

>  E_r,v can only change to earlier after round r completes and we may indeed need to wait for it to change to earlier to progress.

> 
means?

**Comment by james-ray** [comment]
I want to ask one more question, what do you think of CFFG?  consider of performance?

I think if network goes well, maybe CFFG will behave better? for it needs only 1 round vote, Grandpa needs 2 rounds.

But if network goes not well, Grandpa will have better converge performance. Plus Grandpa can finalize some blocks each round, so the transaction confirm time will be more stable than CFFG.

**Comment by james-ray** [comment]
The 3rd question is: Is the requirement of completing round r-1 to enter round r not a requirement of safety, but an improvement for convergence, together with the Primary Vote Mechanism?  It requires all the nodes to begin decreasing their Er-1,v to let them make the choice whether or not follow the Primary Vote based on that decreased Er-1,v?

**Comment by AlistairStewart** [comment]
In answer to your first question, yes, during round r, E_r,v can both move higher or lower. If it ever goes lower or in future rounds, it can only go lower. We will also want a round to be completable if E_r,v=g(V_r,v), because we'll normally finalise that, and that is why we need this impossible for C_r ,v to have a supermajority for any children of g(V_r,v) condition.

Your example works if we change the numbers. With 1/2,1/2 we always think it is possible for C_r,v to have a supermajority for B, though this could only happen if 1/6 equivocate. If less than 1/3 precommit for B, say 1/6, then we may advance to the next round r seeing 1/6 for B,  1/2 for A. At this point, we have finalised A, but E_r-1,v=B. If the precommits we see for A goes up to 2/3, then E_r-1,v drops to B. People who saw these votes first might prevote for some C >A on a different chain to B. If enough do, then we'll have g(V_r,v)=C. Then, yes, we may have to wait to see the precommits for A, so that E_r-1,v drops to A, before proceeding.

In answer to your 3rd question, no, waiting for the round to be completable is necessary for safety. If we haven't yet seen all the prevotes then it's possible that other honest guys are precommiting some B that is > our g(V_r,v) and so B might be finalised in round r, even though B > E_r,v. When the round is completable, we know that this won't happen. If we wait for completability , then any honest vote in the next round is a descendent of anything that could be finalised in an earlier round, which immediately gives that any block that is finalised in this round is a descendent of any block finalised in an earlier round i.e. safety.

**Comment by AlistairStewart** [comment]
As for Casper FFG, GRANDPA has two advantages, Firstly that it doesn;t need checkpoints and secondly that it's provable live in a sensible model. Plausible liveness is a much weaker property. 

As long as the possible liveness attacks on Capser FFG are not an issue, it is more efficient if you choose the right checkpoint length in the regime where the time it takes to gather votes is much longer than the block time or probabilistic finality time. To finalise anything, we need a one checkpoint long vote sometimes i.e. to have probabilistic finality on the last checkpoint before voting, then do all the votes and get them on chain before the next checkpoint.

For GRANDPA, we just need T to be longer than the network delay. If that works then it doesn't matter so much how long a block takes or how many blocks before we get good probabilstic finality for the undelying fork choice rule. It can scale ok from agreeing on 1 block to agreeing on 100. Casper FFG has problems if we have a checkpoint every block.

**Comment by james-ray** [comment]
@AlistairStewart  Thanks! With your illustration in detail, I got to understand why we have to complete r-1 in order to enter round r.

Below is what I got from your explanation about the consensus algorithm:
Let C_r and V_r  stands for a global view of the prevotes and precommits and assuming there is a gap between g(C_r) and g(V_r). Then the lowest impossible block on a possible chain of C_r is g(C_r)+1, I think maybe we can define a symbol l(C_r,v) to illustrate it, as we receive more precommits in C_r, the l(C_r,v) gradually decreases to g(C_r)+1. If we define this gap interval as an "Acceptable Er,v Regress Interval"  Then what we want to ensure is next round's prevotes should all > some block in the Interval(at least for honest nodes). The first block in the Interval is g(V_r), it is the highest block that could be finalized in round r, what we want to ensure is every honest node should prevote based on it in the next round.

For the Casper FFG, I'm not sure I understand all of your points.
When you said
> Plausible liveness is a much weaker property.
> 
Do you mean though casper FFG's liveness can be proved, it can often be "stuck" in the votes for two or more competing forks?

In the latter part of CFFG paper, it mainly discusses how to handle dynamic validators change. One of its problem is Attack from dynamic validator sets, which means the old set could choose not to include votes on a fork chain so the dynasty doesn't increase on their forked chain. CFFG seems to be able to solve this by introducing two sets: the front set and the rear set.

In Grandpa, we could consider each round of vote is kind of like a dynasty, so there exists a clear border of each dynasty, there won't be a problem that the dynasty will increase or not.  I'm still looking into Grandpa Paper to see how validator set change works.

And what's the problem if we have a checkpoint every block using CFFG?

**Comment by james-ray** [comment]
I have some questions in the Chapter 5 in Grandpa Paper
in 5.1.1 Changing the voter set in an asynchronously safe way
...
When some block B 0 that is m blocks after B has been finalised, then the new voter set starts again at
round 1 with E 0 = B 0

Suppose H(B0)=H(B)+m ,   and some round r can finalize a block H(B0)-5, how do we count the round r+1 prevotes? In [H(B0)-5,H(B0)) we use the old set, In [H(B0),...] we use the new set?
what if both H(B0)-1 and H(B0)+3 got finalized by two different voter set, should we adopt a similar stitching mechanism like CFFG? using front set and rear set? 

In 5.1.2
Unsafe fallback for changing the voter set after stalling

You proposes 2 solutions for solving offline issue,
There is a sentence in solution 1 that I not quite understand
> then they set a new voter set to be one determined by the
900th block since the last commit message on chain.
> 
There is not a commit message in the recent 1000 blocks, the 900th block can how to determine a voter set?

And I don't quite understand solution 2 either
> then they switch to the best validator set given by block n
> 
the n how to determine a voter set?

**Comment by james-ray** [comment]
Really thanks @AlistairStewart  ,  it's all because of your explanation in detail that makes me understand more about the algorithm. 

Since the orignal question has already been answered, I'd close this issue.

Maybe I could open a new issue to discuss the comparison to CFFG and dynamic validators change. If you have time to :)

**Comment by AlistairStewart** [comment]
What the new validator set should be is not part of the GRANDPA protocol. But how we decide when to change to a validator set that we agreed to on chain is relevant. The chain can decide the validator set any way it wants. For Polkadot we'll use NPoS, but Substrate users likely have other options that would work perfectly well with GRANDPA.

I'm not sure github issues are the best way to ask questions about these things but I'll answer them whichever way.

**Comment by james-ray** [comment]
My email is JamesRayLei@gmail.com . @AlistairStewart  Would you please send me an email?   If I can ask you through email, it will be great honor to me.
